version: '3'
services:
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongodata:
