version: '3'
services:
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: